const chokidar = require('chokidar')
const fs = require('fs')
const { basename, dirname } = require('path')

chokidar
  .watch('posts', {
    ignored: (path, stats) =>
      stats &&
      stats.isDirectory() &&
      ['components', 'assets', 'hooks'].includes(basename(path)),
  })
  .on('add', (path) => {
    const destinationPath = `pages/${path}`
    if (!fs.existsSync(destinationPath)) {
      const contents = `
<!-- DO NOT EDIT THIS FILE DIRECTLY IT WAS AUTO-GENTERATED FROM NEXT.CONFIG.JS -->

import Content from '../../../${path}'
export default Content
`.trim()
      fs.mkdirSync(dirname(destinationPath), { recursive: true })
      fs.writeFileSync(destinationPath, contents)
    }
  })

module.exports = {
  pageExtensions: ['mdx'],
  webpack(config, options) {
    config.module.rules.push({
      test: /\.mdx$/,
      use: [options.defaultLoaders.babel, '@mdx-js/loader'],
    })
    return config
  },
}
